### ISSUE TITLE
Run, Present and Export commands not working as expected.

### ISSUE THREAD

**Issue by mlsteiner** [TrevorSayre/Processing.tmbundle#1]
Hi Trevor, thanks for creating this bundle!

Having trouble getting TextMate 2 to execute the 'Run Sketch', 'Present Sketch' and any of the 'Export' commands correctly. Selecting one of these commands from the Bundle Menu [ or invoking via the key command ] flashes 'processing.mode.java.Commander' in the menu bar for a few milliseconds before dropping me back into TextMate. As far as I can tell, the sketch is never compiled and nothing is logged to Console.app.

I have Symlinked my Processing documents folder to a folder in my Dropbox [ to sync with work computer ], but I see the same results even if I revert to the standard setup.

The rest of the bundle [ auto complete etc ] is amazing, so would love to see this working correctly.

Kind regards.
## 

Mac OS X 10.8 [ 10.8.4 ]
TextMate 2 [ 2.0-alpha.9459 ]
Processing 2 [ 2.0.1 ] & processing-java installed
processing.tmbundle [ current develop version ]

**Comment by TrevorSayre** [comment]
I haven't touched this in a while. Thank you for the issue report. I'll take a look at this and see if I can revive the project.

**Comment by mlsteiner** [comment]
Thanks Trevor, I have since been able to test with a different Mac and found the error to be with my setup, not your bundle. Uninstalling and reinstalling the bundle and processing-java seems to have corrected the issue.
Sorry for the inconvenience!

**Comment by TrevorSayre** [comment]
Great news, thank you for getting back to me. I will probably still go through with a big update to this bundle in the near future.

**Comment by mlsteiner** [comment]
Sorry Trevor, I _am_ having trouble getting this to work reliably. I consistently experience what I initially reported and have had to install the MacroMates [processing bundle](https://github.com/textmate/processing.tmbundle) to get TextMate to run a Sketch.

If you did have the time to look into updating your bundle I would be very appreciative!

**Comment by TrevorSayre** [comment]
Updated compatibility to latest Processing 2.1.1
