### ISSUE TITLE
Installation instructions would be nice

### ISSUE THREAD

**Issue by bennigraf** [TrevorSayre/Processing.tmbundle#3]
Hi!
As stated, installation instructions in the readme would be nice. http://blog.macromates.com/2011/locating-bundles/ doesn't work for me (since I don't have the folders they talk about - do I have to set them up myself?). I installed it into TextMate2.app for now.

**Comment by madc** [comment]
Download the hole repo as a zip. Unzip it and rename the unzipped folder(!) to "Processing.tmbundle". Double-click it and install.

![install](https://cloud.githubusercontent.com/assets/343392/3892020/397931b2-222f-11e4-9a37-748f97e550b8.png)

**Comment by bennigraf** [comment]
Thank you :-)
